//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"

@class NSArray, NSSet, NSString, SKProductsRequest, SKReceiptRefreshRequest;

@interface TrgameIAP : NSObject <SKPaymentTransactionObserver, SKProductsRequestDelegate>
{
    _Bool _isRequestingProducts;
    _Bool _isRefreshingProductsList;
    id <TrgameIAPDelegate> _IAPdelegate;
    NSArray *_products;
    NSSet *_productIDS;
    SKProductsRequest *_productRequest;
    SKReceiptRefreshRequest *_receiptRefreshRequest;
    CDUnknownBlockType _receiptRefreshCallback;
}

//@property(copy) CDUnknownBlockType receiptRefreshCallback; // @synthesize receiptRefreshCallback=_receiptRefreshCallback;
//@property(retain) SKReceiptRefreshRequest *receiptRefreshRequest; // @synthesize receiptRefreshRequest=_receiptRefreshRequest;
//@property(retain) SKProductsRequest *productRequest; // @synthesize productRequest=_productRequest;
//@property(retain) NSSet *productIDS; // @synthesize productIDS=_productIDS;
//@property(retain) NSArray *products; // @synthesize products=_products;
//@property _Bool isRefreshingProductsList; // @synthesize isRefreshingProductsList=_isRefreshingProductsList;
//@property _Bool isRequestingProducts; // @synthesize isRequestingProducts=_isRequestingProducts;
//@property(retain) id <TrgameIAPDelegate> IAPdelegate; // @synthesize IAPdelegate=_IAPdelegate;
//- (void)startRefreshReceipt:(CDUnknownBlockType)arg1;
//- (void)request:(id)arg1 didFailWithError:(id)arg2;
//- (void)requestDidFinish:(id)arg1;
//- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
//- (void)paymentQueue:(id)arg1 updatedDownloads:(id)arg2;
//- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
//- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
//- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
//- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
//- (_Bool)isProductRestored:(const char *)arg1;
//- (void)getProductsByIdentifiers:(id)arg1;
//- (void)refreshProductsList:(id)arg1;
//- (void)verifyApp;
//- (_Bool)restoreCompletedIAP;
- (_Bool)buyItem:(id)arg1;
//- (void)initItems:(id)arg1;
//- (void)setDelegate:(id)arg1;

// Remaining properties
//@property(readonly, copy) NSString *debugDescription;
//@property(readonly, copy) NSString *description;
//@property(readonly) unsigned long long hash;
//@property(readonly) Class superclass;

@end

